class ScheduleDesign:
    def __init__(self):
        self.accountSelectParams:list[dict] = [
            {'name': '账号', 'paramName': 'userIds', 'dataType': 'str', 'componentType': 'QLineEdit', 'initial': '','itemsPre':None,'placeholderText':'多账号，以逗号(,)隔开'},
            {'name': '国家', 'paramName': 'country', 'dataType': 'str', 'componentType': 'QComboBox', 'initial': 'getAccountCountries', 'itemsPre':['所有国家','未划分国家']},
            {'name': '省份', 'paramName': 'province', 'dataType': 'str', 'componentType': 'QComboBox', 'initial': 'getAccountProvinces', 'itemsPre':['所有省份','未划分省份']},
            {'name': '城市', 'paramName': 'city', 'dataType': 'str', 'componentType': 'QComboBox', 'initial': 'getAccountCities', 'itemsPre':['所有城市','未划分城市']},
            {'name': '地区', 'paramName': 'region', 'dataType': 'str', 'componentType': 'QComboBox', 'initial': 'getAccountRegions', 'itemsPre':['所有地区','未划分地区']},
            {'name': '行业', 'paramName': 'industry', 'dataType': 'str', 'componentType': 'QComboBox', 'initial': 'getAccountIndustries', 'itemsPre':['所有行业','未划分行业']},
            {'name': '备注', 'paramName': 'remark', 'dataType': 'str', 'componentType': 'QComboBox', 'initial': 'getAccountRemarks', 'itemsPre':['所有备注','未设备注']},
        ]
        self.scheduleList:list[dict] = [
            {'name': '导入群链接', 'function': 'onImportGroups', 'taskName': 'IMPORT_GROUP_INFO','withAccountParams': False,'paramsDescription':'导入时为群分类及分段执行',
             'params': [
                 {'name': '群链接', 'paramName': 'groupLinks', 'dataType': 'str', 'componentType': 'QLineEdit',
                  'initial': '', 'itemsPre': None, 'placeholderText': '群链接名（请用换行/逗号/空格，其中一个符号分隔）'},
                 {'name': '所属国家', 'paramName': 'country', 'dataType': 'str', 'componentType': 'QLineEdit',
                  'initial': '', 'itemsPre': None, 'placeholderText': '所属国家'},
                 {'name': '所属省份', 'paramName': 'province', 'dataType': 'str', 'componentType': 'QLineEdit',
                  'initial': '', 'itemsPre': None, 'placeholderText': '所属省份'},
                 {'name': '所属城市', 'paramName': 'city', 'dataType': 'str', 'componentType': 'QLineEdit',
                  'initial': '', 'itemsPre': None, 'placeholderText': '所属城市'},
                 {'name': '所属地区', 'paramName': 'region', 'dataType': 'str', 'componentType': 'QLineEdit',
                  'initial': '', 'itemsPre': None, 'placeholderText': '所属地区'},
                 {'name': '所属行业', 'paramName': 'industry', 'dataType': 'str', 'componentType': 'QLineEdit',
                  'initial': '', 'itemsPre': None, 'placeholderText': '所属行业'},
                 {'name': '分段执行', 'paramName': 'threads', 'dataType': 'int', 'componentType': 'QLineEdit',
                  'initial': '', 'itemsPre': None, 'placeholderText': '分段执行'},
             ]},
            {'name': '封号检测', 'function': 'onDetermineDisable', 'taskName': 'DETERMINE_DISABLE', 'withAccountParams': True, 'params': None},
            {'name': '受限检测', 'function': 'onDetermineRestricted', 'taskName':'DETERMINE_RESTRICTED', 'withAccountParams': True,  'params': None},
            {'name': '添加会话', 'function': 'onAddSession', 'taskName': 'AUTO_LOGIN', 'withAccountParams': True, 'params': None},
            # {'name': '创建机器人', 'function': 'onApplyForRobot', 'taskName': 'CREATE_ROBOT', 'withAccountParams': True, 'params': None},
            {'name': '刷新机器人token', 'function': 'onRefreshRobotToken', 'taskName': 'REFRESH_ROBOT_TOKEN', 'withAccountParams': True, 'params': None},
            {'name': '机器人加入群', 'function': 'onBotEnterGroup', 'taskName': 'BOT_ENTER_GROUP', 'withAccountParams': True, 'params': None},
            {'name': '加入群', 'function': 'onEnterGroup', 'taskName':'ENTER_GROUP', 'withAccountParams': True, 'paramsDescription':'筛选群链接', 'params': [
                {'name': '指定群', 'paramName': 'groupNames', 'dataType': 'str', 'componentType': 'QLineEdit', 'initial': '',
                 'itemsPre': None,'placeholderText':'多群链接，以逗号(,)隔开'},
                {'name': '国家', 'paramName': 'country', 'dataType': 'str', 'componentType': 'QComboBox',
                 'initial': 'getGroupCountries', 'itemsPre': ['所有国家', '未划分国家']},
                {'name': '省份', 'paramName': 'province', 'dataType': 'str', 'componentType': 'QComboBox',
                 'initial': 'getGroupProvinces', 'itemsPre': ['所有省份', '未划分省份']},
                {'name': '城市', 'paramName': 'city', 'dataType': 'str', 'componentType': 'QComboBox',
                 'initial': 'getGroupCities', 'itemsPre': ['所有城市', '未划分城市']},
                {'name': '地区', 'paramName': 'region', 'dataType': 'str', 'componentType': 'QComboBox',
                 'initial': 'getGroupRegions', 'itemsPre': ['所有地区', '未划分地区']},
                {'name': '行业', 'paramName': 'industry', 'dataType': 'str', 'componentType': 'QComboBox',
                 'initial': 'getGroupIndustries', 'itemsPre': ['所有行业', '未划分行业']},
                {'name': '备注', 'paramName': 'remark', 'dataType': 'str', 'componentType': 'QComboBox',
                 'initial': 'getGroupRemarks', 'itemsPre': ['所有备注', '未设备注']},
            ]},
            {'name': '采集群成员', 'function': 'onCollectGroupMembers', 'taskName': 'COLLECT_GROUP_MEMBERS', 'withAccountParams': True,
             'params': [
                 {'name': '是否添加到通讯录', 'paramName': 'isImport', 'dataType': 'str', 'componentType': 'QComboBox',
                  'initial': '',
                  'itemsPre': ['不添加', '添加']},
                 {'name': '采集方式', 'paramName': 'collectWay', 'dataType': 'str', 'componentType': 'QComboBox',
                  'initial': '',
                  'itemsPre': ['通过成员列表采集', '通过聊天信息采集']},
                 {'name': '采集指定群数后退出执行', 'paramName': 'memberOfGroupToDo', 'dataType': 'int', 'componentType': 'QLineEdit',
                  'initial': '','itemsPre': None, 'placeholderText': '默认数为1'},
             ]},
            {'name': '遍历群信息', 'function': 'onCollectGroupInfo', 'taskName': 'COLLECT_GROUP_INFO', 'withAccountParams': True, 'params': None},
            {'name': '拉用户进群', 'function': 'onAddUserInGroup', 'taskName': 'ADD_USER_IN_GROUP', 'withAccountParams': True, 'params': None},
            {'name': '普通号私发', 'function': 'onSendNormalMsg', 'taskName': 'SEND_NORMAL_MSG', 'withAccountParams': True, 'params': [
                {'name': '消息', 'paramName': 'messageId', 'dataType': 'int', 'componentType': 'QComboBox', 'initial': 'getPrettingMessages',
                 'itemsPre': None,'placeholderText':None},
                {'name': '执行数量', 'paramName': 'messageCount', 'dataType': 'int', 'componentType': 'QLineEdit',
                 'initial': '50','itemsPre': None, 'placeholderText': None},
            ]},
            {'name': '普通号群发', 'function': 'onSendGroupMsg', 'taskName': 'SEND_GROUP_MSG', 'withAccountParams': True, 'params': [
                {'name': '消息', 'paramName': 'messageId', 'dataType': 'int', 'componentType': 'QComboBox',
                 'initial': 'getPrettingMessages',
                 'itemsPre': None, 'placeholderText': None},
                {'name': '执行数量', 'paramName': 'messageCount', 'dataType': 'int', 'componentType': 'QLineEdit',
                 'initial': '50', 'itemsPre': None, 'placeholderText': None},
                {'name': '选择群', 'paramName': 'groupSelected', 'dataType': 'str', 'componentType': 'QComboBox', 'initial': '',
                 'itemsPre': [{'title': '所有群', 'value': 'all'},
                              {'title': '所有自建群', 'value': 'my'},
                              {'title': '所有用户群', 'value': 'user'}],
                 },
            ]},
            {'name': '机器人群发', 'function': 'onSendGroupMsgByRobot', 'taskName': 'SEND_GROUP_MSG_BY_ROBOT', 'withAccountParams': True, 'params': [
                {'name': '消息', 'paramName': 'messageId', 'dataType': 'int', 'componentType': 'QComboBox',
                 'initial': 'getPrettingMessages',
                 'itemsPre': None, 'placeholderText': None},
                {'name': '执行数量', 'paramName': 'messageCount', 'dataType': 'int', 'componentType': 'QLineEdit',
                 'initial': '50', 'itemsPre': None, 'placeholderText': None},
            ]},
            {'name': '互发消息', 'function': 'onSendMsgToEachOther', 'taskName': 'SEND_MSG_TO_EACH_OTHER',
             'withAccountParams': True, 'params': [
                {'name': '随机选择用户发送', 'paramName': 'count', 'dataType': 'int', 'componentType': 'QLineEdit',
                 'initial': '0', 'itemsPre': None, 'placeholderText': None},
                {'name': '发送现有对话', 'paramName': 'isSendExists', 'dataType': 'str', 'componentType': 'QComboBox',
                 'initial': '',
                 'itemsPre': [{'title': '选择', 'value': True},
                              {'title': '未选', 'value': False}],
                 },
            ]},
            {'name': '群名称行业分类', 'function': 'onIndustryClassification', 'taskName': '',
             'withAccountParams': False, 'params': [
                {'name': '执行方式', 'paramName': 'way', 'dataType': 'str', 'componentType': 'QComboBox',
                 'initial': '',
                 'itemsPre': [{'title':'倒序自停','value':'descAuto'},
                              {'title':'倒序全表','value':'desc'},
                              {'title':'正序自停','value':'ascAuto'},
                              {'title':'正序全表','value':'asc'}], 'placeholderText': None},
                {'name': '线程数', 'paramName': 'threads', 'dataType': 'int', 'componentType': 'QLineEdit',
                 'initial': '3', 'itemsPre': None, 'placeholderText': None},
                {'name': '包括已确认分类', 'paramName': 'isIncludeConfirmed', 'dataType': 'bool',
                 'componentType': 'QCheckBox', 'initial': '', 'itemsPre': None, 'placeholderText': None},
            ]},
        ]