# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiDlgLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 160)
        Dialog.setMinimumSize(QtCore.QSize(300, 160))
        Dialog.setMaximumSize(QtCore.QSize(300, 160))
        self.editAccount = QtWidgets.QLineEdit(Dialog)
        self.editAccount.setGeometry(QtCore.QRect(49, 20, 200, 24))
        self.editAccount.setObjectName("editAccount")
        self.editPwd = QtWidgets.QLineEdit(Dialog)
        self.editPwd.setGeometry(QtCore.QRect(49, 60, 200, 24))
        self.editPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPwd.setObjectName("editPwd")
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setGeometry(QtCore.QRect(60, 120, 70, 23))
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(170, 120, 70, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.labelMsg = QtWidgets.QLabel(Dialog)
        self.labelMsg.setGeometry(QtCore.QRect(10, 80, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelMsg.setFont(font)
        self.labelMsg.setStyleSheet("color: rgb(170, 0, 0);")
        self.labelMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMsg.setObjectName("labelMsg")

        self.retranslateUi(Dialog)
        self.btnCancel.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "登录"))
        self.editAccount.setPlaceholderText(_translate("Dialog", "请输入 账号/电话号/邮箱"))
        self.editPwd.setPlaceholderText(_translate("Dialog", "请输入 密码"))
        self.btnOk.setText(_translate("Dialog", "登录"))
        self.btnCancel.setText(_translate("Dialog", "取消"))
        self.labelMsg.setText(_translate("Dialog", "msg"))
