# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiDlgConfirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 150)
        Dialog.setMinimumSize(QtCore.QSize(300, 150))
        Dialog.setMaximumSize(QtCore.QSize(330, 150))
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(170, 100, 70, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("padding:4px;")
        self.btnCancel.setAutoDefault(True)
        self.btnCancel.setObjectName("btnCancel")
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setGeometry(QtCore.QRect(60, 100, 70, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnOk.setFont(font)
        self.btnOk.setStyleSheet("padding:4px;")
        self.btnOk.setAutoDefault(False)
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.labelMsg = QtWidgets.QLabel(Dialog)
        self.labelMsg.setGeometry(QtCore.QRect(9, 20, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelMsg.setFont(font)
        self.labelMsg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMsg.setWordWrap(True)
        self.labelMsg.setObjectName("labelMsg")

        self.retranslateUi(Dialog)
        self.btnOk.clicked.connect(Dialog.accept) # type: ignore
        self.btnCancel.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "操作确认"))
        self.btnCancel.setText(_translate("Dialog", "取消"))
        self.btnOk.setText(_translate("Dialog", "确定"))
        self.labelMsg.setText(_translate("Dialog", "msg"))
