# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiDlgTableShowSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 340)
        Dialog.setMinimumSize(QtCore.QSize(400, 340))
        Dialog.setMaximumSize(QtCore.QSize(400, 340))
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 381, 271))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget.setObjectName("listWidget")
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setGeometry(QtCore.QRect(220, 300, 75, 23))
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(310, 300, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.btnUp = QtWidgets.QPushButton(Dialog)
        self.btnUp.setGeometry(QtCore.QRect(20, 300, 50, 23))
        self.btnUp.setObjectName("btnUp")
        self.btnDown = QtWidgets.QPushButton(Dialog)
        self.btnDown.setGeometry(QtCore.QRect(80, 300, 50, 23))
        self.btnDown.setObjectName("btnDown")

        self.retranslateUi(Dialog)
        self.btnCancel.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "显示设置"))
        self.btnOk.setText(_translate("Dialog", "确定"))
        self.btnCancel.setText(_translate("Dialog", "取消"))
        self.btnUp.setText(_translate("Dialog", "上移"))
        self.btnDown.setText(_translate("Dialog", "下移"))
