# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiDlgPathSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(390, 160)
        Dialog.setMinimumSize(QtCore.QSize(390, 160))
        Dialog.setMaximumSize(QtCore.QSize(390, 160))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 24, 71, 16))
        self.label.setObjectName("label")
        self.lineEditPCClientPath = QtWidgets.QLineEdit(Dialog)
        self.lineEditPCClientPath.setGeometry(QtCore.QRect(100, 22, 191, 20))
        self.lineEditPCClientPath.setObjectName("lineEditPCClientPath")
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(210, 110, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setGeometry(QtCore.QRect(100, 110, 75, 23))
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.btnOpen = QtWidgets.QPushButton(Dialog)
        self.btnOpen.setGeometry(QtCore.QRect(300, 20, 75, 23))
        self.btnOpen.setObjectName("btnOpen")
        self.lineEditWebData = QtWidgets.QLineEdit(Dialog)
        self.lineEditWebData.setGeometry(QtCore.QRect(100, 62, 191, 20))
        self.lineEditWebData.setObjectName("lineEditWebData")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 64, 71, 16))
        self.label_2.setObjectName("label_2")
        self.btnOpen2 = QtWidgets.QPushButton(Dialog)
        self.btnOpen2.setGeometry(QtCore.QRect(300, 60, 75, 23))
        self.btnOpen2.setObjectName("btnOpen2")

        self.retranslateUi(Dialog)
        self.btnCancel.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "路径设置"))
        self.label.setText(_translate("Dialog", "客户端路径："))
        self.btnCancel.setText(_translate("Dialog", "取消"))
        self.btnOk.setText(_translate("Dialog", "确定"))
        self.btnOpen.setText(_translate("Dialog", "浏览"))
        self.label_2.setText(_translate("Dialog", "浏览器数据："))
        self.btnOpen2.setText(_translate("Dialog", "浏览"))
