# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiPagination.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(830, 30)
        Form.setWindowTitle("")
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(160, 2, 108, 25))
        self.widget1.setObjectName("widget1")
        self.btnFirst = QtWidgets.QPushButton(self.widget1)
        self.btnFirst.setGeometry(QtCore.QRect(0, 0, 50, 23))
        self.btnFirst.setObjectName("btnFirst")
        self.btnPrevious = QtWidgets.QPushButton(self.widget1)
        self.btnPrevious.setGeometry(QtCore.QRect(54, 0, 50, 23))
        self.btnPrevious.setObjectName("btnPrevious")
        self.widget3 = QtWidgets.QWidget(Form)
        self.widget3.setGeometry(QtCore.QRect(380, 2, 431, 25))
        self.widget3.setObjectName("widget3")
        self.btnNext = QtWidgets.QPushButton(self.widget3)
        self.btnNext.setGeometry(QtCore.QRect(0, 0, 50, 23))
        self.btnNext.setObjectName("btnNext")
        self.btnLast = QtWidgets.QPushButton(self.widget3)
        self.btnLast.setGeometry(QtCore.QRect(54, 0, 50, 23))
        self.btnLast.setObjectName("btnLast")
        self.label = QtWidgets.QLabel(self.widget3)
        self.label.setGeometry(QtCore.QRect(140, 0, 61, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBoxPageSize = QtWidgets.QComboBox(self.widget3)
        self.comboBoxPageSize.setGeometry(QtCore.QRect(190, 0, 60, 23))
        self.comboBoxPageSize.setObjectName("comboBoxPageSize")
        self.labelTotal = QtWidgets.QLabel(self.widget3)
        self.labelTotal.setGeometry(QtCore.QRect(260, 0, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelTotal.setFont(font)
        self.labelTotal.setObjectName("labelTotal")
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(290, 2, 50, 25))
        self.widget2.setObjectName("widget2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.btnFirst.setText(_translate("Form", "首页"))
        self.btnPrevious.setText(_translate("Form", "上一页"))
        self.btnNext.setText(_translate("Form", "下一页"))
        self.btnLast.setText(_translate("Form", "末页"))
        self.label.setText(_translate("Form", "每页显示"))
        self.labelTotal.setText(_translate("Form", "共 0 条"))
