# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiDlgScheduleTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(860, 420)
        Dialog.setMinimumSize(QtCore.QSize(860, 420))
        Dialog.setMaximumSize(QtCore.QSize(860, 420))
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setGeometry(QtCore.QRect(330, 380, 75, 23))
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(440, 380, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.btnAdd = QtWidgets.QPushButton(Dialog)
        self.btnAdd.setGeometry(QtCore.QRect(30, 380, 75, 23))
        self.btnAdd.setDefault(False)
        self.btnAdd.setObjectName("btnAdd")
        self.btnDelete = QtWidgets.QPushButton(Dialog)
        self.btnDelete.setGeometry(QtCore.QRect(110, 380, 75, 23))
        self.btnDelete.setDefault(False)
        self.btnDelete.setObjectName("btnDelete")

        self.retranslateUi(Dialog)
        self.btnCancel.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "任务计划表"))
        self.btnOk.setText(_translate("Dialog", "确定"))
        self.btnCancel.setText(_translate("Dialog", "取消"))
        self.btnAdd.setText(_translate("Dialog", "添加"))
        self.btnDelete.setText(_translate("Dialog", "批量删除"))
