# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiHome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 820)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 250, 245);")
        self.centralwidget.setObjectName("centralwidget")
        self.mailToolbar = QtWidgets.QWidget(self.centralwidget)
        self.mailToolbar.setGeometry(QtCore.QRect(880, 0, 701, 40))
        self.mailToolbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mailToolbar.setStyleSheet("")
        self.mailToolbar.setObjectName("mailToolbar")
        self.labelAppIcon = QtWidgets.QLabel(self.mailToolbar)
        self.labelAppIcon.setGeometry(QtCore.QRect(10, 0, 40, 40))
        self.labelAppIcon.setStyleSheet("border-radius: 20px;\n"
"background-color: rgba(255, 255, 255,0);")
        self.labelAppIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAppIcon.setObjectName("labelAppIcon")
        self.btnSetting = QtWidgets.QPushButton(self.mailToolbar)
        self.btnSetting.setGeometry(QtCore.QRect(540, 0, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnSetting.setFont(font)
        self.btnSetting.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnSetting.setStyleSheet("QPushButton {\n"
"border-width:0;\n"
"background-color: rgba(255,255,255,0)\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(240,240,255);\n"
"border:1 solid rgba(0,0,200,0.3);\n"
"}\n"
"")
        self.btnSetting.setIconSize(QtCore.QSize(32, 32))
        self.btnSetting.setFlat(False)
        self.btnSetting.setObjectName("btnSetting")
        self.comboBoxDepartment = QtWidgets.QComboBox(self.mailToolbar)
        self.comboBoxDepartment.setGeometry(QtCore.QRect(150, 8, 140, 24))
        self.comboBoxDepartment.setObjectName("comboBoxDepartment")
        self.btnAccount = QtWidgets.QPushButton(self.mailToolbar)
        self.btnAccount.setGeometry(QtCore.QRect(620, 0, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnAccount.setFont(font)
        self.btnAccount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnAccount.setStyleSheet("QPushButton {\n"
"border-width:0;\n"
"background-color: rgba(255,255,255,0)\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(240,240,255);\n"
"border:1 solid rgba(0,0,200,0.3);\n"
"}\n"
"")
        self.btnAccount.setIconSize(QtCore.QSize(32, 32))
        self.btnAccount.setFlat(False)
        self.btnAccount.setObjectName("btnAccount")
        self.btnSchedule = QtWidgets.QPushButton(self.mailToolbar)
        self.btnSchedule.setGeometry(QtCore.QRect(430, 0, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnSchedule.setFont(font)
        self.btnSchedule.setStyleSheet("QPushButton {\n"
"border-width:0;\n"
"background-color: rgba(255,255,255,0)\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(240,240,255);\n"
"border:1 solid rgba(0,0,200,0.3);\n"
"}\n"
"")
        self.btnSchedule.setIconSize(QtCore.QSize(32, 32))
        self.btnSchedule.setFlat(False)
        self.btnSchedule.setObjectName("btnSchedule")
        self.checkBoxWinOnTop = QtWidgets.QCheckBox(self.mailToolbar)
        self.checkBoxWinOnTop.setGeometry(QtCore.QRect(60, 8, 80, 24))
        self.checkBoxWinOnTop.setStyleSheet("QCheckBox {\n"
"border:1 solid rgba(0,0,200,0);\n"
"padding:5px;\n"
"}\n"
"QCheckBox:hover{\n"
"background-color: rgb(240,240,255);\n"
"border:1 solid rgba(0,0,200,0.3);\n"
"padding:5px;\n"
"}\n"
"")
        self.checkBoxWinOnTop.setChecked(False)
        self.checkBoxWinOnTop.setObjectName("checkBoxWinOnTop")
        self.comboBoxDataType = QtWidgets.QComboBox(self.mailToolbar)
        self.comboBoxDataType.setGeometry(QtCore.QRect(310, 8, 101, 24))
        self.comboBoxDataType.setObjectName("comboBoxDataType")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("border-bottom-left-radius: 8px;\n"
"color: rgb(255, 255, 127);\n"
"background-color: rgb(100, 100, 100);\n"
"border-bottom-right-radius: 8px;")
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UI自动化"))
        self.labelAppIcon.setText(_translate("MainWindow", "图标"))
        self.btnSetting.setText(_translate("MainWindow", "设置"))
        self.btnAccount.setText(_translate("MainWindow", "登录"))
        self.btnSchedule.setText(_translate("MainWindow", "任务计划"))
        self.checkBoxWinOnTop.setText(_translate("MainWindow", "窗口置顶"))
