# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 80)
        Dialog.setMinimumSize(QtCore.QSize(400, 80))
        Dialog.setMaximumSize(QtCore.QSize(400, 80))
        self.btnRun = QtWidgets.QPushButton(Dialog)
        self.btnRun.setGeometry(QtCore.QRect(220, 30, 80, 23))
        self.btnRun.setAutoDefault(False)
        self.btnRun.setObjectName("btnRun")
        self.btnSetting = QtWidgets.QPushButton(Dialog)
        self.btnSetting.setGeometry(QtCore.QRect(90, 30, 80, 23))
        self.btnSetting.setAutoDefault(False)
        self.btnSetting.setObjectName("btnSetting")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "737+SETE7彩金赠送分析表采集定时任务"))
        self.btnRun.setText(_translate("Dialog", "运行"))
        self.btnSetting.setText(_translate("Dialog", "设置"))
