# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 250)
        Dialog.setMinimumSize(QtCore.QSize(400, 250))
        Dialog.setMaximumSize(QtCore.QSize(400, 250))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 20))
        self.label.setObjectName("label")
        self.plainTextEdit737 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit737.setGeometry(QtCore.QRect(110, 20, 261, 71))
        self.plainTextEdit737.setObjectName("plainTextEdit737")
        self.plainTextEditSete7 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEditSete7.setGeometry(QtCore.QRect(110, 100, 261, 71))
        self.plainTextEditSete7.setObjectName("plainTextEditSete7")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 101, 20))
        self.label_2.setObjectName("label_2")
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setGeometry(QtCore.QRect(80, 200, 80, 23))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(220, 200, 80, 23))
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(Dialog)
        self.btnOK.clicked.connect(Dialog.accept) # type: ignore
        self.btnCancel.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Token配置"))
        self.label.setText(_translate("Dialog", "737会话Token:"))
        self.label_2.setText(_translate("Dialog", "SETE7会话Token:"))
        self.btnOK.setText(_translate("Dialog", "确定"))
        self.btnCancel.setText(_translate("Dialog", "取消"))
